combine linting and type checking workflows (#219)
* combine linting and type checking workflows

* rename workflow

* test continue-on-error

* test failure log

* fix formatting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,7 +34,7 @@ jobs:
           python3 -m pip install '.[dev]'
 
   format:
-    name: Linting check
+    name: Lint and type check
     if: github.event.pull_request.draft == false
     runs-on: ubuntu-latest
     timeout-minutes: 2
@@ -54,35 +54,33 @@ jobs:
           python3 -m pip install --upgrade pip
           python3 -m pip install '.[dev]'
       - name: Run ruff format
-        run: |
-          checks/format_.py
+        id: ruff-format
+        run: checks/format_.py
+        continue-on-error: true
       - name: Run ruff check
-        run: |
-          checks/lint_.py
-
-  mypy:
-    name: Type check
-    if: github.event.pull_request.draft == false
-    runs-on: ubuntu-latest
-    timeout-minutes: 2
-    needs: install
-    steps:
-      - uses: actions/checkout@v4
-      - name: Set up Python 3.11
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
-      - uses: actions/cache@v4
-        with:
-          path: ${{ env.pythonLocation }}
-          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml', 'build-cython.py') }}
-      - name: Install package and dependencies
-        run: |
-          python3 -m pip install --upgrade pip
-          python3 -m pip install '.[dev]'
+        id: ruff-check
+        run: checks/lint_.py
+        continue-on-error: true
       - name: Run mypy
+        id: mypy
+        run: checks/mypy_.py
+        continue-on-error: true
+      - name: Check for failures
         run: |
-          checks/mypy_.py
+          FAILED=0
+          if [ ${{ steps.ruff-format.outcome }} != 'success' ]; then
+            echo "ruff format failed"
+            FAILED=1
+          fi
+          if [ ${{ steps.ruff-check.outcome }} != 'success' ]; then
+            echo "ruff check failed"
+            FAILED=1
+          fi
+          if [ ${{ steps.mypy.outcome }} != 'success' ]; then
+            echo "mypy failed"
+            FAILED=1
+          fi
+          exit $FAILED
 
   coverage:
     name: Pytest and coverage check
@@ -105,5 +103,4 @@ jobs:
           python3 -m pip install --upgrade pip
           python3 -m pip install '.[dev]'
       - name: Run coverage
-        run: |
-          checks/coverage_.py
+        run: checks/coverage_.py
